### PR TITLE
Use lsb_release to calculate ubunto version

### PR DESCRIPTION
**Pull request by Meir017**

### CODE REVIEW

**Comment by mxschmitt** [comment]
Thank you for your Pull Request, does this PR fix something or is there an issue with more details?

**Comment by Meir017** [comment]
This pr just simplifies the way we calculate the Ubuntu version

**Comment by Meir017** [comment]
@mxschmitt I think this approach is more simple and easy to understand

**Comment by mxschmitt** [comment]
Closing for now, since it does not fix anything and we usually recommend npx playwright install —with-deps instead.

**Pull request closed without merging**
